### ISSUE TITLE
Error information reduced when handled by the store

### ISSUE THREAD

**Issue by nherment** [mirceaalexandru/seneca-mysql-store#18]
Instead of having

```
{ [Error: ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG: Dynamic SQL is not allowed in stored function or trigger]
  code: 'ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG',
  errno: 1336,
  sqlState: '0A000',
  index: 0 }
```

The error displays as
```
2015-03-25T14:33:34.395Z	83abaactibg9/1427294013981/62171/-	ERROR	plugin	mysql-store	BWK	{eraro=true,orig=,code=entity/error,seneca={code=entity/error,valmap={code=ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG,errno=1336,sqlState=0A000,index=0}},package=seneca,msg=seneca: entity/error,details={code=ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG,errno=1336,sqlState=0A000,index=0},callpoint=at error (/Users/nherment/workspace/vision-live/nodejs-payload-extractor/node_modules/seneca-mysql-store/mysql-store.js:109:14)}
2015-03-25T14:33:34.396Z	83abaactibg9/1427294013981/62171/-	ERROR	act	mysql-store	BWK	OUT	re8lrbbzmxs6/0u75gujj4kuq	role:entity,cmd:save	15	{cmd=save,role=entity,ent={length=74,latitude=53.134952545166,longitude=-6.0814452171326,vehicle_speed=0,vehicle_heading=197,sat_visible=144,sat_used=53,hdop=248,status_gsm=0,status_moving=0,status_heart_beat=0,status_gps=1,status_engine_state=1,status_backup_battery_failure=0,<LEN>=17},name=event,base=sys}	ENTRY	A;1zy48uf5fmg9	-	seneca: entity/error	entity/error	{code=ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG,errno=1336,sqlState=0A000,index=0,plugin={}}	Error: seneca: entity/error
    at errormaker (/Users/nherment/workspace/vision-live/nodejs-payload-extractor/node_modules/seneca/node_modules/eraro/eraro.js:94:15)
    at Seneca.root.fail (/Users/nherment/workspace/vision-live/nodejs-payload-extractor/node_modules/seneca/seneca.js:188:21)
    at error (/Users/nherment/workspace/vision-live/nodejs-payload-extractor/node_modules/seneca-mysql-store/mysql-store.js:109:14)
    at Query.<anonymous> (/Users/nherment/workspace/vision-live/nodejs-payload-extractor/node_modules/seneca-mysql-store/mysql-store.js:294:16)
    at Query.report [as _callback] (/Users/nherment/workspace/vision-live/nodejs-payload-extractor/node_modules/seneca-mysql-store/mysql-store.js:70:19)
    at Query.Sequence.end (/Users/nherment/workspace/vision-live/nodejs-payload-extractor/node_modules/seneca-mysql-store/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query.ErrorPacket (/Users/nherment/workspace/vision-live/nodejs-payload-extractor/node_modules/seneca-mysql-store/node_modules/mysql/lib/protocol/sequences/Query.js:93:8)
    at Protocol._parsePacket (/Users/nherment/workspace/vision-live/nodejs-payload-extractor/node_modules/seneca-mysql-store/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/Users/nherment/workspace/vision-live/nodejs-payload-extractor/node_modules/seneca-mysql-store/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/Users/nherment/workspace/vision-live/nodejs-payload-extractor/node_modules/seneca-mysql-store/node_modules/mysql/lib/protocol/Protocol.js:39:16)
```

which is cryptic and not actionable.

Same goes for errors on a specific field or a specific table.

**Comment by r4j4h** [comment]
I don't have a great answer for you, but I figured I'd share my thoughts since no one has responded to you yet..

You are right, the Error string itself is missing, the`[Error: ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG: Dynamic SQL is not allowed in stored function or trigger]` bit.

However, do note that the rest of the information is there:

`{code=ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG,errno=1336,sqlState=0A000,index=0...}`

Although not in a terribly friendly format, it is at least actionable. :)

**Comment by nherment** [comment]
ohh you're right, I missed that..
it's just weird and annoying formatting.

Closing this ;)

**Comment by nherment** [comment]
thx a lot btw !

**Comment by r4j4h** [comment]
You are very welcome! I am glad I could help =)
